0:
  - /home/rodrigo/Documents/GABI/test/bigwig/mac.bw
  - /home/rodrigo/Documents/GABI/test/bigwig/mic.bw
1:
  - /home/rodrigo/Documents/GABI/test/bigwig/slip.bw
  - /home/rodrigo/Documents/GABI/test/bigwig/slap.bw